name: Test
on: [push]
jobs:
  test:
    name: ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        gemfile:
          - gemfiles/rubocop_1.41.gemfile
          - gemfiles/rubocop_1.8.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_7.0.gemfile
        exclude:
          - ruby: 3.0
            gemfile: gemfiles/rubocop_1.8.gemfile
          - ruby: 3.1
            gemfile: gemfiles/rubocop_1.8.gemfile
          - ruby: 3.2
            gemfile: gemfiles/rubocop_1.8.gemfile
          - ruby: 3.3
            gemfile: gemfiles/rubocop_1.8.gemfile

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rake
